from assistant_app import (
    APP_DIR,
    CHAT_MODES,
    DEFAULT_EMBED_MODEL,
    DEFAULT_LOG_LEVEL,
    DEFAULT_MODEL,
    DEFAULT_VAULT_PATH,
    LOG_DIR,
    LOG_FILE,
    MAX_PROMPT_CHARS,
    MAX_UPLOAD_SIZE_MB,
    SUPPORTED_UPLOAD_TYPES,
    StartupResult,
    VOKSEWERK_GREEN,
    VOKSEWERK_NAVY,
    AppConfig,
    AppStatus,
    build_audit_prompt,
    build_status,
    build_vault_index,
    clear_chat_history,
    configure_logging,
    configure_models,
    count_vault_documents,
    ensure_session_state,
    get_chat_readiness,
    initialize_app,
    load_config,
    load_vault_documents,
    main,
    maybe_reset_chat_for_mode,
    normalize_log_level,
    read_uploaded_case,
    run_case_audit,
    run_strategic_query,
    validate_environment,
    validate_prompt,
    with_status,
)


if __name__ == "__main__":
    main()
